# Generated by Django 6.0.1 on 2026-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_boarding', models.IntegerField()),
                ('inflight_wifi', models.IntegerField()),
                ('seat_comfort', models.IntegerField()),
                ('cleanliness', models.IntegerField()),
                ('travel_class', models.CharField(max_length=20)),
                ('type_of_travel', models.CharField(max_length=30)),
                ('flight_distance', models.IntegerField()),
                ('total_delay', models.IntegerField()),
                ('prediction', models.CharField(max_length=30)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
